//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovernmentFeesEn
    {
        public string DepartmentCode { get; set; }
        public string DepartementName { get; set; }
        public string ActivityUnifiedElectronicCode { get; set; }
        public string ActivityDescription { get; set; }
        public string SectorClassification { get; set; }
        public string EconomicClassification { get; set; }
        public string PricingCategory { get; set; }
        public string CollectionPeriodical { get; set; }
        public string GovernmentNaturalState { get; set; }
        public string Status { get; set; }
        public string BeneficiaryType { get; set; }
        public string SourceOfRevenue { get; set; }
        public string FixedVariable { get; set; }
        public string FeesInLegislation { get; set; }
        public string LegislationNumber { get; set; }
        public string LegislationYear { get; set; }
        public string PublishingAbility { get; set; }
        public int ID { get; set; }
    }
}
