//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobClassificationOfExpens
    {
        public Nullable<double> Year { get; set; }
        public string JobClassificationOfExpenses { get; set; }
        public string JobClassificationOfExpensesEn { get; set; }
        public Nullable<double> TotalExpenses { get; set; }
        public int ID { get; set; }
        public Nullable<int> GroupID { get; set; }
    }
}
