//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenDataEntities : DbContext
    {
        public OpenDataEntities()
            : base("name=OpenDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GovernmentFee> GovernmentFees { get; set; }
        public virtual DbSet<GovernmentFeesEn> GovernmentFeesEns { get; set; }
        public virtual DbSet<JobClassificationOfExpens> JobClassificationOfExpenses { get; set; }
        public virtual DbSet<RevenueByEconomicClassification> RevenueByEconomicClassifications { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<RevenuesByFunctionalSector> RevenuesByFunctionalSectors { get; set; }
        public virtual DbSet<TotalExpens> TotalExpenses { get; set; }
    }
}
