//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenuesByFunctionalSector
    {
        public Nullable<double> Year { get; set; }
        public string SectorsByJob { get; set; }
        public Nullable<double> TotalRevenue { get; set; }
        public int ID { get; set; }
        public string SectorsByJobEn { get; set; }
    }
}
